version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: books_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books_db
      MYSQL_USER: books_user
      MYSQL_PASSWORD: books_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 